### ISSUE TITLE
nerfstudio setup question

### ISSUE THREAD

**Issue by ccarlsonpb** [hturki/pynerf#5]
Hello, I tried running your code and the results quality is impressive. Unfortunately I'm running into some issues that I suspect are related to my setup process. 

I ran `ns-process-data` as normal, but running `ns-train` gives me this error:

```FileNotFoundError: [Errno 2] No such file or directory: 'data/test/poses_bounds.npy'```

I have a utility script from another project to generate this file, and I figured it's pretty standard across nerf projects, but after generating said file and training, I noticed my cameras / bounds were all wrong. Seems like it's as simple as swapping the Y and Z axes in the camera poses, but I'm wondering where the disconnect actually is since this isn't mentioned anywhere.

**Comment by hturki** [comment]
We adopt the same data conventions as the rest of Nerfstudio: https://docs.nerf.studio/quickstart/data_conventions.html

Are you running into coordinate/bound issues when running with nerfstudio's default nerfacto method?

One thing to double-check is whether you're using the correct dataparser. For example, the PyNeRF method uses the mipnerf360 dataparser by default: https://github.com/hturki/pynerf/blob/main/pynerf/pynerf_method_config.py#L26 

Which you potentially want to change to the nerfstudio data parser in your case:

```
ns-train pynerf nerfstudio-data --data <your data dir>
```

Let me know if things still don't work!

**Comment by ccarlsonpb** [comment]
Hi @hturki , thanks for the reply. Every other nerfstudio model works without issue - i.e. I train with this command:
`ns-train {model} --data {nerfstudio_data_path}`

The data in the path is generated like so:
`ns-process-data images --data {images_path} --output-dir {nerfstudio_data_path} --matching-method exhaustive`

And `{images_path}` simply contains 9 images of a subject (colmap resolves them all correctly).

So the whole process follows nerfstudio convention end-to-end.

When running pynerf, I had to make a few code changes (fixing broken paths) to get it running - and it does run, and trains to completion, but the axes / bounds are totally wrong and this breaks rendering because of gimbal lock or something similar (the camera rotates wildly when moving along the path).

I tried your suggestion of changing the dataparser but that does not work either, as I get this error:
```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/pynerf/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/user/miniconda3/envs/pynerf/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/user/miniconda3/envs/pynerf/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/user/miniconda3/envs/pynerf/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/user/miniconda3/envs/pynerf/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/home/user/miniconda3/envs/pynerf/lib/python3.10/site-packages/nerfstudio/engine/trainer.py", line 147, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/home/user/miniconda3/envs/pynerf/lib/python3.10/site-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/home/user/miniconda3/envs/pynerf/lib/python3.10/site-packages/nerfstudio/pipelines/base_pipeline.py", line 263, in __init__
    self.datamanager: DataManager = config.datamanager.setup(
  File "/home/user/miniconda3/envs/pynerf/lib/python3.10/site-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/home/user/miniconda3/envs/pynerf/lib/python3.10/site-packages/pynerf/data/datamanagers/random_subset_datamanager.py", line 120, in __init__
    self.eval_ray_generator = RayGenerator(self.eval_dataparser_outputs.cameras.to(self.device),
  File "/home/user/miniconda3/envs/pynerf/lib/python3.10/site-packages/nerfstudio/model_components/ray_generators.py", line 41, in __init__
    self.register_buffer("image_coords", cameras.get_image_coords(), persistent=False)
  File "/home/user/miniconda3/envs/pynerf/lib/python3.10/site-packages/nerfstudio/cameras/cameras.py", line 306, in get_image_coords
    image_height = torch.max(self.image_height.view(-1)).item()
RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.
```

I just did a clean test, from scratch - created a new conda environment, installed pynerf via `pip install git+https://github.com/hturki/pynerf`, installed the other dependencies `pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch` and `pip install torch-scatter -f https://data.pyg.org/whl/torch-2.1.0+cu121.html` but am getting the same issue. Any ideas?

**Comment by ccarlsonpb** [comment]
quick update - I got it working by changing this line in `random_subset_datamanager.py` in addition to using the `nerfstudio-data` flag with `ns-train`:
```
# self.eval_dataparser_outputs = dataparser.get_dataparser_outputs(split='test')  # test_mode)
self.eval_dataparser_outputs = dataparser.get_dataparser_outputs(split='train')  # test_mode)
```

The `input.numel() == 0` issue it was complaining about seems to be caused by me having too few input images (only 9) - so it seems the test split is empty in my case.

**Comment by hturki** [comment]
Good to hear! One note of caution is that 9 images feels on the lower end of the number of images needed to train a good NeRF, especially for 360-degree views.
